import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, CheckCircle2, CircleHelp, Database, FileSearch, Menu, Scale, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { useState } from "react";
import { Brand } from "./brand";
import { Button } from "@/components/ui/button";
import { GlassCard, GlassPanel, StatusBadge } from "./primitives";

type LucideIcon = typeof FileSearch;
const valueCards: Array<[LucideIcon, string, string]> = [[FileSearch,"查证","从公开来源建立可追溯证据"],[Scale,"判断","区分事实、信号、估算与推断"],[Target,"行动","找出最可能改变结论的未知"],[ShieldCheck,"更新","过期数据不会冒充当前事实"]];
const evidenceCards: Array<[LucideIcon, string]> = [[CheckCircle2,"已验证事实"],[Sparkles,"市场信号"],[Database,"估算"],[BookOpenCheck,"推断"],[CircleHelp,"尚未验证"],[ShieldCheck,"冲突证据"]];

const nav = [["产品","/product"],["工作方式","/method"],["真实数据","/data"],["证据体系","/evidence-system"],["决策系统","/decision-system"],["方案","/pricing-plan"]] as const;
export function SiteHeader() { const [open,setOpen]=useState(false); return <header className="fixed inset-x-0 top-4 z-50 mx-auto w-[calc(100%-24px)] max-w-[1240px] rounded-[22px] glass-panel"><div className="grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center px-4 lg:grid-cols-[auto_1fr_auto] lg:px-5"><Link to="/"><Brand/></Link><nav className="hidden justify-center gap-1 lg:flex">{nav.map(([x,to])=><Link key={x} to={to} className="rounded-xl px-3 py-2 text-sm text-ink-soft hover:bg-glass-strong hover:text-foreground">{x}</Link>)}</nav><div className="hidden items-center gap-2 lg:flex"><Button variant="ghost" asChild><Link to="/login">登录</Link></Button><Button asChild><Link to="/register">开始分析</Link></Button></div><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label="菜单">{open?<X/>:<Menu/>}</Button></div>{open&&<div className="border-t border-border p-3 lg:hidden">{nav.map(([x,to])=><Link key={x} to={to} onClick={()=>setOpen(false)} className="block rounded-xl px-3 py-2 text-sm">{x}</Link>)}<div className="mt-2 grid grid-cols-2 gap-2"><Button variant="outline" asChild><Link to="/login">登录</Link></Button><Button asChild><Link to="/register">开始分析</Link></Button></div></div>}</header>; }

function PreviewWorkspace() { return <GlassPanel className="relative mx-auto mt-16 max-w-6xl overflow-hidden p-3 shadow-2xl"><div className="grid min-h-[500px] grid-cols-[180px_1fr]"><aside className="hidden border-r border-glass-edge p-4 sm:block"><Brand compact/><div className="mt-10 space-y-2">{["工作台","行业","客户","证据","决策"].map((x,i)=><div key={x} className={`rounded-xl px-3 py-2 text-xs ${i===0?'bg-primary text-primary-foreground':'text-muted-foreground'}`}>{x}</div>)}</div></aside><div className="p-4 sm:p-6"><div className="flex items-center justify-between"><div><div className="text-xs text-muted-foreground">当前项目</div><div className="mt-1 font-semibold">决策工作台</div></div><StatusBadge tone="warn">有条件推进</StatusBadge></div><div className="mt-6 grid gap-3 md:grid-cols-[1.3fr_1fr]"><GlassCard className="min-h-52"><span className="text-xs text-muted-foreground">当前建议</span><h3 className="mt-8 text-2xl font-semibold">先验证购买者，<br/>再扩大投入。</h3><p className="mt-4 text-xs leading-5 text-muted-foreground">结论会随着证据更新。</p></GlassCard><div className="grid grid-cols-3 gap-2 md:grid-cols-1">{["可行性","证据","决策"].map(x=><GlassCard className="p-4" key={x}><span className="text-[10px] text-muted-foreground">{x}</span><div className="mt-3 text-sm font-semibold">尚未验证</div></GlassCard>)}</div></div><div className="mt-3 grid gap-3 sm:grid-cols-3">{["支持推进","不利因素","关键未知"].map((x,i)=><GlassCard key={x}><StatusBadge tone={i===0?'good':i===1?'bad':'warn'}>{x}</StatusBadge><div className="mt-7 h-2 w-4/5 rounded-full bg-muted"/><div className="mt-2 h-2 w-3/5 rounded-full bg-muted"/></GlassCard>)}</div></div></div></GlassPanel>; }

export function HomePage() { return <main><SiteHeader/><section className="px-5 pb-20 pt-40 text-center sm:pt-48"><StatusBadge>创业决策智能系统</StatusBadge><h1 className="mx-auto mt-7 max-w-4xl text-5xl font-semibold leading-[1.12] sm:text-6xl lg:text-7xl">一个创业想法，<br/>先查证，再判断。</h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Lumbyte OS 将真实证据、明确未知与可解释模型组织成一套可行动的决策工作流。</p><div className="mt-9 flex justify-center gap-3"><Button size="lg" asChild><Link to="/register">开始分析 <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/method">了解工作方式</Link></Button></div><div className="mt-7 flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs text-muted-foreground"><span>没有数据，不等于结果为 0</span><span>事实与估算严格分开</span><span>结论随证据更新</span></div><PreviewWorkspace/></section>
    <section className="border-y border-glass-edge bg-glass/30 px-5 py-24"><div className="mx-auto max-w-6xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-xs font-semibold text-muted-foreground">为什么是 Lumbyte</span><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">不是更快地产生答案，<br/>而是更清楚地知道答案从何而来。</h2></div><div className="grid gap-4 sm:grid-cols-2">{valueCards.map(([Icon,t,b])=><GlassCard key={t}><Icon className="text-violet-soft"/><h3 className="mt-6 font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></GlassCard>)}</div></div></div></section>
    <section className="px-5 py-24"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><span className="text-xs font-semibold text-muted-foreground">证据体系</span><h2 className="mt-4 text-4xl font-semibold">每一种确定程度，都有自己的名字。</h2></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{evidenceCards.map(([Icon,x])=><GlassCard key={x} className="flex items-center gap-4"><Icon className="text-violet-soft"/><span className="font-medium">{x}</span></GlassCard>)}</div><div className="mt-16 grid gap-4 lg:grid-cols-3">{["定义问题与边界","检索并分类证据","识别客户与替代方案","建立可解释模型","形成当前决策","持续核验与更新"].map((x,i)=><div key={x} className="border-t border-border pt-5"><span className="text-xs text-muted-foreground">0{i+1}</span><h3 className="mt-3 font-semibold">{x}</h3></div>)}</div></div></section>
    <section className="px-5 pb-24"><GlassPanel className="mx-auto max-w-6xl p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><span className="text-xs text-muted-foreground">我们的承诺</span><h2 className="mt-4 text-4xl font-semibold">灵蕴允许自己说不知道。</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">未知不是缺陷，而是下一次验证最有价值的入口。我们不会用虚构数字填满一个看似完整的答案。</p></div><Button size="lg" asChild><Link to="/register">开始你的判断 <ArrowRight/></Link></Button></div></GlassPanel></section><Footer/></main>; }

export function ContentPage({ type }: { type: string }) { const content:Record<string,[string,string,string[]]>={product:["产品","把散落的研究，组织成一个可以持续更新的决策系统。",["行业与客户研究","竞品与定价证据","财务与风险建模","决策与最终报告"]],method:["工作方式","从提出问题到形成决策，每一步都保留证据边界。",["定义","查证","分类","建模","判断","更新"]],data:["真实数据","数据必须能说明来源、地域、期间与最近核验时间。",["来源可追溯","时效可识别","地域不混用","未知不写成零"]],"evidence-system":["证据体系","不同的确定程度，不应被包装成同一种答案。",["已验证事实","市场信号","估算","推断","尚未验证","冲突证据"]],"decision-system":["决策系统","当前建议不是终点，而是当前证据下最诚实的判断。",["支持推进","不利因素","关键未知","升级条件","降级条件"]],"pricing-plan":["方案","商业方案将在真实服务准备完成后公布。",["不展示虚构价格","不制造虚假稀缺","按真实能力开放"]],about:["关于 Lumbyte","我们相信好的创业判断，始于对证据边界的尊重。",["真实优先","可解释优先","行动优先"]],terms:["使用条款","本页面为前端设计预览，正式条款将在生产版本提供。",["服务范围","账户责任","知识产权"]],privacy:["隐私政策","本设计预览不收集或存储账户与项目数据。",["数据处理","信息安全","用户权利"]],"ai-data":["AI 与数据声明","AI 参与整理与推理，但不会把推断冒充成事实。",["来源透明","分类明确","人工可复核","结论可更新"]]}; const fallback=content['product']; if(!fallback) return null; const [title,desc,items]=content[type]??fallback; return <main><SiteHeader/><section className="min-h-[75vh] px-5 pb-24 pt-40"><div className="mx-auto max-w-6xl"><span className="text-xs font-semibold text-muted-foreground">Lumbyte OS</span><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-tight sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{desc}</p><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><GlassCard key={x}><span className="text-xs text-muted-foreground">0{i+1}</span><h2 className="mt-10 text-lg font-semibold">{x}</h2></GlassCard>)}</div></div></section><Footer/></main>; }

function Footer(){return <footer className="border-t border-glass-edge px-5 py-10"><div className="mx-auto flex max-w-6xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><Brand/><div className="flex flex-wrap gap-5 text-xs text-muted-foreground"><Link to="/about">关于</Link><Link to="/terms">条款</Link><Link to="/privacy">隐私</Link><Link to="/ai-data">AI 与数据声明</Link></div></div></footer>}