import { ArrowRight, BookOpen, Check, ChevronRight, CircleAlert, Database, ExternalLink, FileDown, Flag, RefreshCw, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { previewDecision, previewEvidence, previewFinancial, projectPreview, type DecisionData, type EvidenceItem, type FinancialData } from "@/lib/fixtures";
import { DataValue, GlassCard, GlassPanel, PageHeading, StatusBadge } from "./primitives";

const metricLabel: Record<string, string> = { viabilityScore: "可行性", evidenceConfidence: "证据置信度", decisionConfidence: "决策置信度" };

export function DecisionView({ data = previewDecision }: { data?: DecisionData }) {
  return <div className="space-y-6"><PageHeading eyebrow="证据与决策 / 决策" title="当前决策" description="结论只依据当前证据，并会随着关键未知被验证而变化。" action={<Button><RefreshCw />重新分析</Button>} />
    <GlassPanel className="overflow-hidden border-warning/20 bg-warning/6 p-6 lg:p-8"><div className="grid gap-8 lg:grid-cols-[1.35fr_1fr]"><div><StatusBadge tone="warn">{data.recommendation}</StatusBadge><h2 className="mt-5 max-w-2xl text-2xl font-semibold leading-snug lg:text-3xl">{data.rationale}</h2><button className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">查看判断依据 <ArrowRight className="h-4 w-4" /></button></div><div className="grid grid-cols-3 gap-3">{(["viabilityScore", "evidenceConfidence", "decisionConfidence"] as const).map((key) => <GlassCard key={key} className="flex min-h-32 flex-col justify-between"><span className="text-xs text-muted-foreground">{metricLabel[key]}</span><span className="text-xl font-semibold"><DataValue value={data[key]} suffix="%" /></span></GlassCard>)}</div></div></GlassPanel>
    <div className="grid gap-4 lg:grid-cols-3"><EvidenceColumn title="支持推进" items={data.positiveEvidence} tone="good" /><EvidenceColumn title="不利因素" items={data.negativeEvidence} tone="bad" /><EvidenceColumn title="关键未知" items={data.criticalUnknowns} tone="warn" /></div>
    <div className="grid gap-4 lg:grid-cols-2"><GlassCard><div className="flex items-center gap-2"><TrendingUp className="text-success"/><h3 className="font-semibold">升级条件</h3></div><p className="mt-4 text-sm leading-6 text-muted-foreground">获得可重复的付费意愿证据，并验证获客成本处于可持续范围。</p></GlassCard><GlassCard><div className="flex items-center gap-2"><Flag className="text-danger-soft"/><h3 className="font-semibold">降级条件</h3></div><p className="mt-4 text-sm leading-6 text-muted-foreground">核心购买者无法确认，或替代方案转换成本显著高于预期。</p></GlassCard></div>
    <GlassPanel className="p-6"><div className="flex items-center justify-between"><div><span className="text-xs text-muted-foreground">下一步最值得验证</span><h2 className="mt-1 text-xl font-semibold">让一个未知更接近事实</h2></div><Target className="text-violet-soft" /></div><div className="mt-5 divide-y divide-border">{data.criticalUnknowns.map((item, i) => <div key={item} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 py-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary text-xs text-primary-foreground">{i+1}</span><span className="text-sm">{item}</span><Button variant="ghost" size="sm">创建验证 <ChevronRight /></Button></div>)}</div></GlassPanel>
  </div>;
}

function EvidenceColumn({ title, items, tone }: { title: string; items: string[]; tone: "good"|"warn"|"bad" }) { return <GlassCard><StatusBadge tone={tone}>{title}</StatusBadge><ul className="mt-5 space-y-4">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-6"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-current" />{item}</li>)}</ul></GlassCard>; }

export function WorkbenchView() { return <div className="space-y-6"><PageHeading eyebrow="工作台" title="早上好，继续把未知变清楚" description="这里聚合当前判断、关键未知与最值得执行的下一步。" action={<Button><Sparkles />继续分析</Button>} /><div className="grid gap-4 xl:grid-cols-[1.45fr_1fr]"><GlassPanel className="p-6"><div className="flex items-center justify-between"><StatusBadge tone="warn">有条件推进</StatusBadge><span className="text-xs text-muted-foreground">随证据更新</span></div><h2 className="mt-7 text-3xl font-semibold">方向值得继续验证，<br/>但还不足以进入规模化投入。</h2><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">优先确认购买者、付费意愿与可持续获客路径。</p><Button variant="outline" className="mt-8">打开完整决策 <ArrowRight /></Button></GlassPanel><div className="grid grid-cols-3 gap-3 xl:grid-cols-1">{["可行性","证据置信度","决策置信度"].map(x=><GlassCard key={x} className="flex items-center justify-between"><span className="text-xs text-muted-foreground">{x}</span><DataValue value={null}/></GlassCard>)}</div></div><div className="grid gap-4 lg:grid-cols-2"><GlassPanel className="p-6"><h2 className="text-lg font-semibold">关键未知</h2><div className="mt-4 space-y-3">{previewDecision.criticalUnknowns.map(x=><div className="rounded-2xl bg-warning/8 p-4 text-sm" key={x}>{x}</div>)}</div></GlassPanel><GlassPanel className="p-6"><h2 className="text-lg font-semibold">研究进度</h2><div className="mt-5 space-y-5">{[["行业边界",true],["客户信号",true],["付费意愿",false],["财务输入",false]].map(([x,ok])=><div className="flex items-center gap-3" key={String(x)}><span className={`grid h-7 w-7 place-items-center rounded-full ${ok?'bg-success/10 text-success':'bg-secondary text-muted-foreground'}`}>{ok?<Check className="h-4 w-4"/>:<span className="h-2 w-2 rounded-full bg-current"/>}</span><span className="text-sm">{x}</span></div>)}</div></GlassPanel></div></div>; }

export function FinancialView({ data = previewFinancial }: { data?: FinancialData }) { const metrics = [["MRR",data.MRR],["ARR",data.ARR],["毛利率",null],["Burn",data.Burn],["Runway",data.Runway],["Break-even",data.BreakEven],["CAC",data.CAC],["LTV",data.LTV]]; return <div className="space-y-6"><PageHeading eyebrow="建模 / 财务" title="财务模型" description="确定性公式只在关键输入完整时输出结果；未知不会被当作零。" action={<Button>补充数据</Button>} /><GlassPanel className="p-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([k,v])=><GlassCard key={String(k)}><span className="text-xs text-muted-foreground">{k}</span><div className="mt-6 text-2xl font-semibold"><DataValue value={v as string|null}/></div></GlassCard>)}</div></GlassPanel><div className="grid gap-4 lg:grid-cols-[1.35fr_1fr]"><GlassPanel className="p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">关键假设</h2><Button variant="ghost" size="sm"><RotateCcw/>恢复系统值</Button></div><div className="mt-4 divide-y divide-border">{data.assumptionOrigins.map(a=><div className="grid grid-cols-[1fr_auto_auto] items-center gap-3 py-4" key={a.label}><span className="text-sm">{a.label}</span><span className="text-sm font-medium">{a.value}</span><StatusBadge tone={a.origin==='尚未验证'?'warn':'neutral'}>{a.origin}</StatusBadge></div>)}</div></GlassPanel><GlassCard className="bg-ice/14"><CircleAlert className="text-violet-soft"/><h2 className="mt-5 text-lg font-semibold">还需要补充这些关键数据</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">目标客单价、月度新增客户与完整交付成本决定模型是否可计算。</p><Button className="mt-6">补充关键数据</Button></GlassCard></div></div>; }

export function EvidenceView({ items = previewEvidence }: { items?: EvidenceItem[] }) { const [query,setQuery]=useState(''); const [selected,setSelected]=useState<EvidenceItem|null>(null); const visible=useMemo(()=>items.filter(x=>x.claim.includes(query)||x.source.includes(query)),[items,query]); return <div className="space-y-6"><PageHeading eyebrow="证据与决策 / 证据" title="证据账本" description="每条结论都保留来源、时效、地域与证据等级。" /><GlassPanel className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索结论或来源" className="h-10 rounded-xl border-glass-edge bg-glass pl-9" /></div><Button variant="outline"><SlidersHorizontal/>筛选</Button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr>{["分类","结论","来源","期间","地域","最近核验"].map(x=><th className="border-b border-border px-3 py-3 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{visible.map((item,i)=><tr key={i} onClick={()=>setSelected(item)} className="cursor-pointer hover:bg-glass"><td className="border-b border-border px-3 py-4"><StatusBadge tone={item.classification==='尚未验证'?'warn':'neutral'}>{item.classification}</StatusBadge></td><td className="max-w-sm border-b border-border px-3 py-4 font-medium">{item.claim}</td><td className="border-b border-border px-3 py-4 text-muted-foreground">{item.source}</td><td className="border-b border-border px-3 py-4">{item.period}</td><td className="border-b border-border px-3 py-4">{item.geography}</td><td className="border-b border-border px-3 py-4">{item.lastChecked}</td></tr>)}</tbody></table></div></GlassPanel>{selected&&<div className="fixed inset-0 z-50 bg-foreground/10 backdrop-blur-sm" onClick={()=>setSelected(null)}><aside className="glass-panel absolute inset-y-3 right-3 w-[min(520px,calc(100vw-24px))] rounded-[28px] p-7" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><StatusBadge>{selected.classification}</StatusBadge><Button variant="ghost" size="icon" onClick={()=>setSelected(null)} aria-label="关闭">×</Button></div><h2 className="mt-8 text-2xl font-semibold">{selected.claim}</h2><dl className="mt-8 space-y-5 text-sm">{[["来源",selected.source],["地域",selected.geography],["期间",selected.period],["最近核验",selected.lastChecked]].map(([a,b])=><div key={a}><dt className="text-xs text-muted-foreground">{a}</dt><dd className="mt-1">{b}</dd></div>)}</dl><Button variant="outline" className="mt-8">查看原始来源 <ExternalLink/></Button></aside></div>}</div>; }

export function ReportView() { return <div className="space-y-6"><PageHeading eyebrow="证据与决策 / 最终报告" title="决策备忘录" description="以可追溯证据组织的当前版本结论。" action={<Button variant="outline"><FileDown/>导出</Button>} /><GlassPanel className="mx-auto max-w-5xl overflow-hidden"><div className="border-b border-glass-edge p-6 sm:p-8"><StatusBadge tone="warn">有条件推进</StatusBadge><h2 className="mt-5 text-3xl font-semibold">新项目：当前决策备忘录</h2><div className="mt-3 text-xs text-muted-foreground">生成时间：设计预览 · 所有业务结论待真实数据接入</div></div><article className="mx-auto max-w-[820px] space-y-12 px-6 py-10 sm:px-10">{["执行摘要","项目与问题定义","市场与行业","目标客户","竞争格局","定价与商业模式","财务模型","主要风险","证据置信度","关键未知","决策结论","Decision Flip","验证优先级","来源"].map((x,i)=><section key={x}><span className="text-xs text-muted-foreground">{String(i+1).padStart(2,'0')}</span><h2 className="mt-2 text-xl font-semibold">{x}</h2><p className="mt-3 text-sm leading-7 text-ink-soft">{i===0?previewDecision.rationale:"暂无可靠公开证据。接入真实 Lumbyte 数据后，此处将按照现有数据契约渲染。"}</p></section>)}</article></GlassPanel></div>; }

const moduleContent: Record<string,{eyebrow:string;title:string;description:string;blocks:{title:string;body:string}[]}>= {
  industry:{eyebrow:"研究 / 行业",title:"行业研究",description:"界定市场边界、驱动因素与约束。",blocks:[{title:"行业定义",body:"当前定义仍需与真实项目输入核对。"},{title:"目标地区",body:projectPreview.region},{title:"规模与趋势",body:"暂无可靠公开证据"},{title:"监管与约束",body:"尚未验证"}]},
  customer:{eyebrow:"研究 / 客户",title:"客户理解",description:"区分实际用户、购买者与决策者。",blocks:[{title:"目标客户",body:"小型创业团队"},{title:"实际用户",body:"创始人与早期研究人员"},{title:"购买者",body:"尚未验证"},{title:"核心任务",body:"降低关键决策中的证据盲区"},{title:"替代方案",body:"分散搜索、表格与人工汇总"},{title:"付费意愿",body:"暂无可靠公开证据"}]},
  competitor:{eyebrow:"研究 / 竞品",title:"竞争格局",description:"比较定位、客户、功能与已核验定价。",blocks:[{title:"直接竞品",body:"尚未验证"},{title:"间接替代",body:"公开搜索与通用协作工具"},{title:"转换成本",body:"待访谈核验"},{title:"定价可比性",body:"暂无可靠公开证据"}]},
  pricing:{eyebrow:"研究 / 定价",title:"定价研究",description:"把公开价格与项目假设严格分开。",blocks:[{title:"竞品价格",body:"暂无可靠公开证据"},{title:"当前假设",body:"待用户补充"},{title:"计费单位",body:"尚未验证"},{title:"折扣策略",body:"尚未验证"}]},
  "business-model":{eyebrow:"研究 / 商业模式",title:"商业模式",description:"把价值、收入、分发与成本组织成可验证结构。",blocks:[{title:"价值主张",body:"让早期决策有据可依"},{title:"收入来源",body:"当前假设"},{title:"分发路径",body:"尚未验证"},{title:"关键依赖",body:"持续、可追溯的数据质量"}]},
  risk:{eyebrow:"建模 / 风险",title:"风险地图",description:"风险不是全部标红，而是按证据、概率和影响排序。",blocks:[{title:"市场风险",body:"付费意愿尚未验证"},{title:"执行风险",body:"潜在"},{title:"数据风险",body:"持续核验"},{title:"阻断条件",body:"尚未发现已确认阻断条件"}]},
};

export function ModuleView({ section }: { section: string }) { const fallback=moduleContent.industry; if(!fallback) return null; const content=moduleContent[section]??fallback; return <div className="space-y-6"><PageHeading {...content} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{content.blocks.map((b,i)=><GlassCard key={b.title} className={i===0?'sm:col-span-2':''}><div className="flex items-center justify-between"><h2 className="font-semibold">{b.title}</h2><StatusBadge tone={b.body.includes('尚未')||b.body.includes('暂无')?'warn':'neutral'}>{b.body.includes('尚未')||b.body.includes('暂无')?'待验证':'当前信息'}</StatusBadge></div><p className="mt-8 text-sm leading-6 text-muted-foreground">{b.body}</p></GlassCard>)}</div><GlassPanel className="p-6"><h2 className="text-lg font-semibold">相关证据</h2><div className="mt-4 flex items-center justify-between rounded-2xl bg-glass p-4"><div className="flex items-center gap-3"><Database className="text-violet-soft"/><div><div className="text-sm font-medium">证据将在真实数据接入后显示</div><div className="text-xs text-muted-foreground">不以示例数字填充未知状态</div></div></div><Button variant="ghost">打开证据 <ChevronRight/></Button></div></GlassPanel></div>; }