import { Link } from "@tanstack/react-router";
import { ArrowRight, MoreHorizontal, Plus, Search, Settings2 } from "lucide-react";
import { useState, type FormEvent } from "react";
import { AppShell, PreviewNotice } from "./app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { GlassCard, GlassPanel, PageHeading, StatusBadge } from "./primitives";

export function ProjectsPage() { return <AppShell><PreviewNotice/><div className="space-y-6"><PageHeading eyebrow="项目" title="项目列表" description="打开已有项目，或从一个需要验证的创业想法开始。" action={<Button asChild><Link to="/projects/new"><Plus/>创建项目</Link></Button>} /><GlassPanel className="p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input placeholder="搜索项目" className="h-10 rounded-xl border-glass-edge bg-glass pl-9"/></div></GlassPanel><div className="grid gap-4 lg:grid-cols-2"><GlassCard><div className="flex items-start justify-between"><div><StatusBadge tone="neutral">仅设计预览</StatusBadge><h2 className="mt-5 text-xl font-semibold">新项目</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">为小型创业团队提供基于证据的早期决策工作区</p></div><Button variant="ghost" size="icon" aria-label="项目菜单"><MoreHorizontal/></Button></div><div className="mt-9 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">尚未开始真实分析</span><Button variant="outline" asChild><Link to="/workspace/workbench">打开项目 <ArrowRight/></Link></Button></div></GlassCard><GlassCard className="grid min-h-56 place-items-center border-dashed text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-secondary"><Plus/></div><h2 className="mt-4 font-semibold">创建另一个项目</h2><p className="mt-1 text-sm text-muted-foreground">从一个清晰的问题开始</p></div></GlassCard></div></div></AppShell>; }

export function CreateProjectPage() { const [done,setDone]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true)}; return <AppShell><div className="mx-auto max-w-4xl space-y-6"><PageHeading eyebrow="项目 / 新建" title="你正在考虑什么？" description="先描述想法与目标用户，Lumbyte 将在真实接入后围绕证据而不是想象展开分析。"/><GlassPanel className="p-6 sm:p-8"><form onSubmit={submit} className="space-y-6"><label className="block"><span className="mb-2 block text-sm font-semibold">创业想法</span><Textarea required placeholder="例如：为……提供……，帮助他们解决……" className="min-h-48 rounded-2xl border-glass-edge bg-glass-strong p-5 text-base"/></label><div className="grid gap-4 sm:grid-cols-3">{[["目标地区","中国大陆"],["目标客户","小型创业团队"],["当前阶段","问题验证"]].map(([a,b])=><label key={a}><span className="mb-2 block text-sm font-medium">{a}</span><Input placeholder={b} className="h-12 rounded-xl border-glass-edge bg-glass-strong"/></label>)}</div>{done&&<div className="rounded-xl bg-warning/8 p-4 text-sm text-warning">预览已捕获表单状态，但不会创建项目或调用假接口。</div>}<div className="flex justify-end gap-3"><Button variant="outline" asChild><Link to="/projects">取消</Link></Button><Button type="submit">开始分析 <ArrowRight/></Button></div></form></GlassPanel></div></AppShell>; }

export function SettingsPage() { return <AppShell><div className="mx-auto max-w-4xl space-y-6"><PageHeading eyebrow="项目 / 设置" title="项目设置" description="管理项目基础信息。危险操作保持克制且明确。"/><GlassPanel className="p-6"><div className="flex items-center gap-3"><Settings2 className="text-violet-soft"/><h2 className="text-lg font-semibold">基础信息</h2></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm">项目名称</span><Input defaultValue="新项目" className="h-12 rounded-xl bg-glass-strong"/></label><label><span className="mb-2 block text-sm">目标地区</span><Input defaultValue="中国大陆" className="h-12 rounded-xl bg-glass-strong"/></label></div><Button className="mt-6">保存更改</Button></GlassPanel><GlassPanel className="border-danger-soft/20 p-6"><h2 className="font-semibold text-danger-soft">删除项目</h2><p className="mt-2 text-sm text-muted-foreground">生产接入时必须沿用现有确认与权限逻辑。</p><Button variant="destructive" className="mt-5">删除项目</Button></GlassPanel></div></AppShell>; }